### ISSUE TITLE
Types query pg_type_elem always null

### ISSUE THREAD

**Issue by TravisCardwell** [mzabani/codd#141]
The `pg_type_elem` relation is created using a `LEFT JOIN` as follows ([code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L699)):

```sql
LEFT JOIN pg_catalog.pg_type AS pg_type_elem
  ON pg_type_elem.oid = pg_type.typelem
```

A `WHERE` condition filters rows such that this is always null ([code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L751)):

```sql
pg_type_elem.oid IS NULL
```

If I understand correctly, this means that the object name logic always uses the `ELSE` case because `pg_type_elem.typname` is always null.

The object name is created using the following SQL ([code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L677), [code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L133-L147)):

```sql
CASE
  WHEN pg_type.typelem <> 0
    AND pg_type.typlen = -1
    AND pg_type.typname LIKE '\\_%'
    AND pg_type_elem.typname IS NOT NULL
  THEN pg_type_elem.typname || '[]'
  ELSE pg_type.typname
END
```

In addition, the `element_type` attribute is always null ([code](https://github.com/mzabani/codd/blob/0b31d04ad2b0a04ef5d664bc6608b1dfdbe8f3d0/src/Codd/Representations/Database/Pg10.hs#L656)):

```sql
pg_type_elem.typname
```

By the way, I think it would be really nice to create a test schema that has at least one value for everything that the Codd queries selects, so that there are no nulls, just to use for development and testing.

**Comment by mzabani** [comment]
Super detailed issue, as usual. Thanks :)

This was addressed by https://github.com/mzabani/codd/pull/144.

> By the way, I think it would be really nice to create a test schema that has at least one value for everything that the Codd queries selects, so that there are no nulls, just to use for development and testing.

I don't think I understand this. Can you elaborate? By the way, I'm closing this issue but feel free to reply here.

**Comment by TravisCardwell** [comment]
Ah, sorry for my poor wording!

The idea is just to develop a schema that tests every part of the `SELECT` queries.  Developing the schema and tests would uncover issues like this one.  Golden/unit tests could then be used to check compatibility when refactoring queries.

Perhaps this would need to be implemented using a common SQL file as well as an SQL file for each tested PostgreSQL version, so that any version-specific functionality can also be tested.

For each test PostgreSQL version, the schema should test all parts of the `SELECT` queries for that version.  Without code coverage tooling, it is up to the developer to ensure full coverage.  A query output field that is always null would be a clear indicator of an issue, however.

**Comment by mzabani** [comment]
> Ah, sorry for my poor wording!

No worries, it was perfectly fine, and it makes total sense now as well!

> The idea is just to develop a schema that tests every part of the SELECT queries. Developing the schema and tests would uncover issues like this one.

I think I see now. We'd create fake pg catalog tables with all combinations of values to make sure all branches of our SQL queries are executed. Something akin to fuzzing?

This sounds nice, but I wonder if it's worth the weight of implementing it. IIUC, we'd have to test enough variations of data in the schema tables so that every field of every schema query returns a non null value at least once. If we do this blindly, it sounds like it could be a long running test (or maybe having data for all columns in schema table would be an easy way to spot these)? But also, would it detect non executed branches of our SQL queries or code like the ones you spotted here? I think it wouldn't, as the name of the type returned was always non null anyway.

But it would detect some unused or incorrect parts of our queries; that much is certain. And I'm saying all this but I have no real idea of whether it would be truly that much work to implement.

However, do you think we'd gain much compared to just having tests like https://github.com/mzabani/codd/blob/fef944bdb97cf1586a39eebe23a6ffe89c2a445b/test/DbDependentSpecs/SchemaVerificationSpec.hs#L151-L1051 ? For context, that test specifies SQL statements and what changes are to be expected in the schema when we apply them.

Surely these tests won't detect dead branches in our queries that always lead to null values, but they are necessary for every meaningful feature anyway, so if we make it more comprehensive the likelihood we're forgetting something should be significantly low.
